### ISSUE TITLE
[Crash]: CTD 8.1.0 (DF or/and DW)

### ISSUE THREAD

**Issue by Wolfman8475** [Fuzss/diagonalfences#1]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.1.0

### Notes (Required)

Can only see "failed to load resources" at the main menu before CTD when used with diagonal windows
Seems log spam (can't post it, github crashes)

No crash when 8.0.1 used

### Crash Report (Required)

https://gist.github.com/Wolfman8475/7b42426e3c3873718d65cdbbd0b4da75

**Comment by Fuzss** [comment]
Thanks for reporting! Looks like something is making my runtime resource pack fail to generate the models...

Please send a chunk of your log then containing the errors related to the diagonal mods.

Also any idea what a mod called 'ccm' might be? It is mentioned in the crash.

**Comment by Wolfman8475** [comment]
There is the lastest log: https://gist.github.com/Wolfman8475/067c6fb051cf33a4c5c208d0bd48255f
And which version of Forge Diagonal Fences needs? Because I forgot to mention that I'm on Forge 47.2.0

I don't know about "ccm" I will looking at.

**Comment by Fuzss** [comment]
Thanks! The Forge version is fine. The log confirms once more that my resource generation has failed, but doesn't reveal why.
Can you please do a binary search to find which mod is incompatible? Doesn't seem to be any other way around it unfortunately.

**Comment by 909oce** [comment]
![image](https://github.com/Fuzss/diagonalfences/assets/21692038/3f1d77d2-b5b2-459c-b8ae-4115d02a53a7)

**Comment by 909oce** [comment]
no errors in my logs though

**Comment by 909oce** [comment]
normal fences are the ones that got reverted from update, missing texture is me trying to replace them

**Comment by Fuzss** [comment]
@909oce Please open a separate issue.

**Comment by Fuzss** [comment]
And provide the log.

**Comment by 909oce** [comment]
There is no log lol. I checked the entire log from boot to ingame.

**Comment by 909oce** [comment]
But sure I'll send my log anyway in a new issue, thanks

**Comment by Wolfman8475** [comment]
I disabled one by one, but nothing found. 
So I created a specific CurseForge profile with only Diagonal Fences, Diagonal Windows and Puzzles Lib and nothing changed.
However the crash log seems different: https://gist.github.com/Wolfman8475/3453740fd6d33d5e5df512da70c935b6
And there is the lastest log: https://gist.github.com/Wolfman8475/16d2fdd525bd867443aaeb7e599e7b48

**Comment by Fuzss** [comment]
Looks like something doesn't work on Windows, that's why I wasn't able to spot it during my testing before the release. Will do some more testing on my end.

**Comment by Fuzss** [comment]
Thanks for the help!

**Comment by Wolfman8475** [comment]
I've tried with only Diagonal Fences (without Windows) this time and still crashing...
Here the crashlog: https://gist.github.com/Wolfman8475/31fac082adce491b40932db29c112d5d
and the log: https://gist.github.com/Wolfman8475/cde8bda94d5cf8fe76dd3eab1a047169
Hope it will help!

**Comment by Wolfman8475** [comment]
Seems the issue has been resolved with the 8.1.1! Thank you!

**Comment by Fuzss** [comment]
Thanks for the feedback!
