### ISSUE TITLE
[Suggestion]: Client-only eye candy

### ISSUE THREAD

**Issue by UpYoursMicrosoft** [Fuzss/diagonalfences#15]
### Mod Loader (Optional)

⸺

### Suggestion (Required)

Your mod is awesome and it's the only one I can find that does this in 1.20, but it appears to use its own blocks to make the magic happen. I have a long term survival world and I don't want to introduce any mods with their own blocks so I can easily remove anything later.

I realize I'm probably way out of scope here and the answer will almost certainly be "no", but is it at all possible with the way the mod is currently written to make vanilla fence blocks (visually) connect diagonally without doing the server-side block switching, perhaps with a config option?

**Comment by Fuzss** [comment]
Hey I totally get what you are going for and that is actually how the mod worked prior to version 8.1.0+1.20.1.

I had to move to dedicated blocks unfortunately though as modifying vanilla fences didn't go so well with some other mods and being compatible with as many mods as possible and therefore appealing to modpacks is more important than being able to serve as a drop-in / drop-out for vanilla worlds.

You can either port or have someone port the pre-8.1.0 version, or maybe find / make some block converter that you can use before uninstalling the mod to convert all fences back to vanilla.

**Comment by UpYoursMicrosoft** [comment]
Thanks for your help. That's a very reasonable decision.
