### ISSUE TITLE
[Bug]: Fences show missing models

### ISSUE THREAD

**Issue by papamaionise** [Fuzss/diagonalfences#2]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.1.0

### Notes (Required)

textures not showing correctly
![huge_2023-10-28_00 24 30](https://github.com/Fuzss/diagonalfences/assets/126779287/0f3b3d13-d3d0-4ca8-ae1a-7a281b7b89ca)

**Comment by Fuzss** [comment]
Please provide a log.

**Comment by papamaionise** [comment]
[latest.log](https://github.com/Fuzss/diagonalfences/files/13192615/latest.log)
[2023-10-27-1.log](https://github.com/Fuzss/diagonalfences/files/13192646/2023-10-27-1.log)

issue started after updating the mod from 8.0.1 to 8.1.0 
all previously placed fence blocks are just fine and they diconnect as was mentioned on the mod page but when you place them with the new mod version they show the missing texture block

**Comment by Fuzss** [comment]
So this appears to be a conflict with some other unknown mod. The log is indeed not giving anything away about it.
It would be very helpful if you could do a binary search to find the incompatible mod. Thanks!

The binary search is a way of finding a faulty thing among a lot of other things, without having to remove the things one-by-one.

This is useful for finding a broken mod among hundreds of mods, without having to spend time testing the mods one-by-one.

The procedure is simple:
Remove half of the existing things, and put them aside.
Run the program / game.
Does the issue still exist?
If YES: Repeat from step 1 with the current things.
IF NO: Swap out the current things with the ones set aside, and repeat from step 1.
Repeat this process until the problematic thing/s have been found.

**Comment by Fuzss** [comment]
And can you please test if the mod works on it's own? The issue might be related to you being on Windows..

**Comment by papamaionise** [comment]
> And can you please test if the mod works on it's own? The issue might be related to you being on Windows..

Updated the mod from 8.1.0 to 8.1.1 and it solved the issue 
didn't even removed any mod or resourcepack and im using 100s of them
