### ISSUE TITLE
[Suggestion]: Mod removal

### ISSUE THREAD

**Issue by EfficientStinkbug** [Fuzss/diagonalfences#20]
### Mod Loader (Optional)

NeoForge

### Minecraft Version(s) (Optional)

1.20.4

### Suggestion (Required)

Since this mod doesn't just add new fences but also changes the vanilla ones, that means if the mod is removed all the fences disappear. (The original mod "fence overhaul" just added diagonal variants). Is there a way to prevent that? If diagonal fences ever get implemented to Vanilla MC and s world would be updated to a future version, all the fences would disappear, not just the diagonal ones.

**Comment by Fuzss** [comment]
You can now sneak + right-click fences with an empty hand to convert them back to vanilla.
