### ISSUE TITLE
[Bug]: Missing textures

### ISSUE THREAD

**Issue by 909oce** [Fuzss/diagonalfences#3]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.1.0

### Notes (Required)

Log: https://mclo.gs/2e9g8YW

I am 99% sure this is the same issue as the other bug reports, the only reason my log is different is because I'm using Modernfix to dynamically load resources so it's not creating an error at runtime. Loading without Modernfix creates the same log with baked models failing like the other reports.

**Comment by Fuzss** [comment]
So this appears to be a conflict with some other unknown mod. The log is indeed not giving anything away about it.
It would be very helpful if you could do a binary search to find the incompatible mod. Thanks!

The binary search is a way of finding a faulty thing among a lot of other things, without having to remove the things one-by-one.

This is useful for finding a broken mod among hundreds of mods, without having to spend time testing the mods one-by-one.

The procedure is simple:
Remove half of the existing things, and put them aside.
Run the program / game.
Does the issue still exist?
If YES: Repeat from step 1 with the current things.
IF NO: Swap out the current things with the ones set aside, and repeat from step 1.
Repeat this process until the problematic thing/s have been found.

**Comment by Fuzss** [comment]
Fixed in latest version.
