### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ciellix** [Fuzss/diagonalfences#31]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

v21.1.1

### Minimal Setup (Required)

No

### Notes (Required)

Game will not load up, it just gets stuck on this screen, waited 5 mins+ and nothing
![sddssfsdf](https://github.com/user-attachments/assets/31cefc15-57fa-4b31-a60d-0cf1f6e35690)

### latest.log (Required)

https://mclo.gs/Nfqzkot

**Comment by Fuzss** [comment]
Update Diagonal Walls.

**Comment by Ciellix** [comment]
yep, that was the issue, my bad, thanks tho
