### ISSUE TITLE
[Crash]: Rendering Overlay

### ISSUE THREAD

**Issue by casualfan0** [Fuzss/diagonalfences#4]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

DiagonalFences-v8.1.0-1.20.1-Forge

### Notes (Required)

I use the forge application to play modded mc. This crashed with several other mods, so I tested it only using this one on another game profile and it still crashed. I used this mod without issues before.

### Crash Report (Required)

https://gist.github.com/casualfan0/bee7732e356a524a5933987ab373d18d

**Comment by Fuzss** [comment]
Fixed in latest version.
