### ISSUE TITLE
[Crash]: Render issue (Diagonal Fences/Windows)

### ISSUE THREAD

**Issue by HyprPosition** [Fuzss/diagonalfences#5]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

both v8.1.0

### Notes (Required)

The crash is during startup. Presumably a mod interaction. The issue exists with both "Diagonal Fences" and "Diagonal Windows", and the issue seems to be the same between them. I've loaded them individually but have not tried them without my other mods present. I am making the assumption that they work normally without the mods though.

### Crash Report (Required)

https://gist.github.com/HyprPosition/bc4cf201ad14766a3d28be248a977dc9

**Comment by Fuzss** [comment]
Fixed in latest version.
